[package]
name = "scrom-provider"
version = "0.1.0"
authors = ["William Huang <will.h86@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
listenfd = "0.3"
actix-files = "0.1.7"
